name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v1
    - name: make
      run: make -j
    - name: make run
      run: make run -j
